// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNYJvGevcMqhjQu3Hx8jz9e6XxTqbLLw',
    appId: '1:770334452974:web:04b678f81a1dc13a0997ff',
    messagingSenderId: '770334452974',
    projectId: 'echo-realm-6d3ba',
    authDomain: 'echo-realm-6d3ba.firebaseapp.com',
    storageBucket: 'echo-realm-6d3ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_9t1mXB9K-yrFyjkoWWeGC4gJHYI1Yk',
    appId: '1:770334452974:android:a6c2d1c8a1ccb56d0997ff',
    messagingSenderId: '770334452974',
    projectId: 'echo-realm-6d3ba',
    storageBucket: 'echo-realm-6d3ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIAqinBIgx_Ngd2wLyQ_IfXfi6xTEspU4',
    appId: '1:770334452974:ios:5cc605f1921520e30997ff',
    messagingSenderId: '770334452974',
    projectId: 'echo-realm-6d3ba',
    storageBucket: 'echo-realm-6d3ba.firebasestorage.app',
    iosBundleId: 'com.example.echorealm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIAqinBIgx_Ngd2wLyQ_IfXfi6xTEspU4',
    appId: '1:770334452974:ios:5cc605f1921520e30997ff',
    messagingSenderId: '770334452974',
    projectId: 'echo-realm-6d3ba',
    storageBucket: 'echo-realm-6d3ba.firebasestorage.app',
    iosBundleId: 'com.example.echorealm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvNYJvGevcMqhjQu3Hx8jz9e6XxTqbLLw',
    appId: '1:770334452974:web:d20cb9ec252f97f30997ff',
    messagingSenderId: '770334452974',
    projectId: 'echo-realm-6d3ba',
    authDomain: 'echo-realm-6d3ba.firebaseapp.com',
    storageBucket: 'echo-realm-6d3ba.firebasestorage.app',
  );
}
